### ISSUE TITLE
Add ability to modify the filename

### ISSUE THREAD

**Issue by chuckf** [bwklein/asciidoc-image-helper#2]
Currently a pasted image uses the name of the doc and a hash as the file name when it is pasted in. I would like the ability to modify the file name that is used when pasting an image into the document. 

My thought would be this is either a pop up dialog box for complete naming flexibility or an option to add a custom field to the file name. 

Currently it is my_asciidoc_file-56fe6.png

A custom field might allow me to put my name or other identifier in there for image tracking purposes.

The custom field would make it look something like this my_asciidoc_file-56fe6-chuck.png

**Comment by bwklein** [comment]
I like this idea and will look into how to make it happen.

**Comment by bwklein** [comment]
@ldez I started a new branch [custom-filenames](https://github.com/bwklein/asciidoc-image-helper/tree/custom-filenames) to try to use a modal panel to capture user input and bring that string back into the filename if the user checks this option in the settings panel.

I was going off a few different examples for this, and I am still working on getting it to work here, but if you could take a look and see what you think that would be great.

**Comment by ldez** [comment]
ok

**Comment by ldez** [comment]
Please use a linter:
- install https://atom.io/packages/linter and https://atom.io/packages/linter-coffeelint
- or execute the following command:  
```shell
coffeelint -f coffeelint.json lib/*.coffee spec/*-spec.coffee
```

**Comment by ldez** [comment]
can you create PR flag as WIP to facilitate the review ?

**Comment by bwklein** [comment]
@ldez I have added a PR #21 and labeled it WIP.  I have also added a few line notes to point out areas of confusion for me.  Thank you for taking a look.

**Comment by bwklein** [comment]
Moved to https://github.com/asciidoctor/atom-asciidoc-image-helper/issues/8
