### ISSUE TITLE
URL support not working on Mac OS X

### ISSUE THREAD

**Issue by chuckf** [bwklein/asciidoc-image-helper#20]
Using Atom 1.7.3 and asciidoc-image-helper 0.9.2, when I paste a path to an image file that path pastes in and does not convert to an image:: link as expected. 

The test path I have used is:

/Users/chuckf/Downloads/splunk.png
/Users/chuckf/Downloads/splunk.jpg

Expected result is

image::splunk.png
image::splunk.jpg

Actual result:

/Users/chuckf/Downloads/splunk.png
/Users/chuckf/Downloads/splunk.jpg

NOTE: When pasting similar paths on a Fedora box, same versions of the software, the URLs are converted to image:: links as expected.

**Comment by ldez** [comment]
Thanks for reporting.

There is  a success popup  or there is an error popup or nothing?

Can you open the Console windows <kbd>ctrl+shift+I</kbd> (I don't know the shortcut for OSX) and see if errors occurs ?

**Comment by chuckf** [comment]
I don't get a success or error message popup. 

I opened the console window with `cmd-alt-i` (for future reference) and did not see any errors occur when pasting in the link.

**Comment by ldez** [comment]
Do you copy the path of your image file as text from a text document or from a file of your system ?

**Comment by chuckf** [comment]
I typed the paths into a text editor, HTML page, and ran the command 'ls /Users/chuckf/Downloads/splunk.png' into the native terminal and iterm2. I then selected the text and copied using `cmd-c` and pasted into Atom using `cmd-v`.

**Comment by ldez** [comment]
I will used a friend's computer to try to reproduce.

**Comment by bwklein** [comment]
Moved to new project under asciidoctor organization.
https://github.com/asciidoctor/atom-asciidoc-image-helper/issues/7
