### ISSUE TITLE
Multiple monitor desktop screenshot only pastes the first desktop

### ISSUE THREAD

**Issue by chuckf** [bwklein/asciidoc-image-helper#4]
I use a second monitor running Mac OS X El Capitan. 

When using the screenshot feature and copying straight to the clipboard (ctrl-command-shift-4), screenshots of individual windows or a selected region of an individual screen is pasted into the adoc file and saved to the images directory as expected. 

However, if I chose to screenshot the entire desktop (ctrl-command-shift-3) and paste it into my adoc file only the main screen is pasted and saved to the images directory. I lose the desktop image that is the second screen. If I save the entire desktop screenshot to a file on the desktop (command-shift-4) two PNG images are saved, one for each monitor. 

Additionally if I select a region that crosses screens, capture the image to the clipboard, and paste to an adoc, it is saved in a distorted way. However if that image is saved to the desktop, it appears as expected. (This is probably an OS limitation, but mentioned for completeness)

**Comment by bwklein** [comment]
This seems to be an OS X thing only.  In Windows I get one large image that spans both screens.  I don't think there is much I can do in the package to get at both clipboard images.
I would suggest going to desktop and then using the full path copy option for OS X, as shown in the updated README file.
