### ISSUE TITLE
Giant thumbnail picture instead of my screenshot

### ISSUE THREAD

**Issue by sharkberto** [bwklein/asciidoc-image-helper#6]
Naming of file is ok, but there seems to be a faulty creation of a reference to the screenshot image within the folder after I copy-paste the image into my atom text editor

![generic-connector-af80b](https://cloud.githubusercontent.com/assets/4588331/15057149/ccda9fbe-12eb-11e6-9123-52404b856a9e.png)

**Comment by bwklein** [comment]
What key command are you using to make the screenshot?
Is the image attached to this issue the file that is placed in the images directory?

You should just be able to use the screenshot key command and then paste directly into the editor.
I am not sure how copying an image from a folder and then pasting into the editor will work.

**Comment by bwklein** [comment]
I noticed that on my PC if I want to copy and paste from an existing file on my system, that I have to open it in an image preview program, in my case Windows Photos and copy from there.  Then the clipboard has image data in it that this package can write to a file in the correct location and will insert the proper image reference.

**Comment by bwklein** [comment]
My guess is that on OS X, there is image data associated with a file object copy, that is probably the thumbnail or icon as you have shown here.

**Comment by bwklein** [comment]
On OS X, try taking the screenshot with Command-Shift-Control-4 and then pasting directly into the Atom editor.

**Comment by bwklein** [comment]
@sharkberto Did the information above resolve your issue?

**Comment by chuckf** [comment]
I was able to duplicate this issue on my Mac with the following process:

1. Open finder to a directory with an image.
2. 'right click' or double finger the touchpad to bring up the context menu and select copy.
3. Paste into the adoc file and the thumbnail is saved as shown in the original report.

Following the same step selecting an image on a web page works as expected. 
A screenshot using Command-Shift-Control-4 works as expected as well.

**Comment by sharkberto** [comment]
I was perhaps not using the recommended approach. Simply pasting the screenshot (taken with cmd ctrl SHIFT + 4) after capture and direct paste into editor does create the correct image in my images folder

**Comment by ldez** [comment]
See #11 this PR allows no longer have to open an image in order to insert it.

**Comment by nicorikken** [comment]
@chuckf Was tricked into the same issue here. The content of the image will have to be copied, rather than the file. Either by making a screenshot using your suggested shortcut (I normally use it without the Ctrl), or by opening the file in say Preview (application), and copying the content using Cmd+c

**Comment by nicorikken** [comment]
Hopefully a working URL-feature will ease this usability.

**Comment by bwklein** [comment]
Please see the new README file for instructions on how to best capture and copy into the editor for OS X and Windows.
